name: academix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.6

dev_dependencies:
  altive_lints: ^1.10.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/svg/
    - .env
